# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: civitas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'civitas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcivitas.proto\x12\x07\x63ivitas\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x86\x01\n\x0c\x41gentRequest\x12\x11\n\trecipient\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12(\n\x07payload\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x16\n\x0e\x63orrelation_id\x18\x04 \x01(\t\x12\x13\n\x0btraceparent\x18\x05 \x01(\t\"E\n\nAgentReply\x12(\n\x07payload\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xac\x01\n\x05\x41gent\x12\x34\n\x06Invoke\x12\x15.civitas.AgentRequest\x1a\x13.civitas.AgentReply\x12\x35\n\x04\x43\x61st\x12\x15.civitas.AgentRequest\x1a\x16.google.protobuf.Empty\x12\x36\n\x06Stream\x12\x15.civitas.AgentRequest\x1a\x13.civitas.AgentReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'civitas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTREQUEST']._serialized_start=86
  _globals['_AGENTREQUEST']._serialized_end=220
  _globals['_AGENTREPLY']._serialized_start=222
  _globals['_AGENTREPLY']._serialized_end=291
  _globals['_AGENT']._serialized_start=294
  _globals['_AGENT']._serialized_end=466
# @@protoc_insertion_point(module_scope)
